services:
  db:
    image: mysql:latest
    container_name: db
    ports:
      - 3360:3360
    env_file:
      - .env.dev
    networks:
      - gql-network
    # change ./data to wherever you want to store the persisted data
    volumes:
      - ./data:/var/lib/mysql

  app:
    build: .
    container_name: graphql-go  
    command: go run ./server/server.go
    ports:
      - 8080:8080
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - gql-network



networks:
  gql-network: